version: '3.1'
services:
  postgres:
    container_name: postgres
    image: postgres:13.0
    environment:
      - DEBUG=false
      - DB_EXTENSION=plpgsql,pg_trgm
      - POSTGRES_USER=hades
      - POSTGRES_PASSWORD=d0nt4get
      - POSTGRES_DB=hades
    ports:
      - "5432:5432"
#    networks:
#      - net1
#
#  api:
#    container_name: tyche_auth_service
#    privileged: true
#    build:
#      context: ./
#      dockerfile: Dockerfile-dev
#    environment:
##      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://hades:d0nt4get@postgres:5432/hades
#      - DATABASE_URL=postgresql+psycopg2://hades:d0nt4get@postgres:5432/hades
#      - FLASK_APP=api
#      - FLASK_DEBUG=1
#      - FLASK_ENV=development
#      - APP_SETTINGS=Development
#    depends_on:
#      - postgres
#    links:
#      - postgres:postgres
#    ports:
#      - "8080:8080"
#    volumes:
#      - ".:/code"
#    networks:
#      - net1
#
#networks:
#  net1:
#    driver: bridge